AllCops:
  NewCops: enable

Style/Alias:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ParallelAssignment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/MixinGrouping:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false  

Style/HashSyntax:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Exclude:
    - "spec/**/*"
  
  CountAsOne:
    - "hash"
    - "array"
    - "heredoc"
    - "method_call"

Naming/BlockForwarding:
  EnforcedStyle: explicit

Style/FrozenStringLiteralComment:
  Enabled: false