
:queues:
  - default
  - active_storage_analysis

:scheduler:
  :dynamic: true
  :schedule:
    run_tasks:
      cron: "0 * * * * *" # every minute
      class: TaskRunner
    purge_orphaned_files:
      cron: "0 0 * * *"
      class: PurgeOrphanedUploadsWorker