name: CI

on:
  release:
    types: [ published ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker version
        run: docker -v

      - name: Check out master
        uses: actions/checkout@main

      - name: Set up Ruby & dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false

      - name: Update SHA
        run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/github_sha

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Build container image
        run: docker build -t registry.digitalocean.com/scoutplan/app:$(echo $GITHUB_SHA | head -c7) -t registry.digitalocean.com/scoutplan/app:latest .

      - name: Add run number to app deployment file
        run: sed -i 's|github-run-number|'${GITHUB_RUN_NUMBER}'|' $GITHUB_WORKSPACE/config/kube/deployment.yml

      - name: Add run number to Sidekiq deployment file
        run: sed -i 's|github-run-number|'${GITHUB_RUN_NUMBER}'|' $GITHUB_WORKSPACE/config/kube/sidekiq.yml

      - name: Update job file
        run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|registry.digitalocean.com/scoutplan/app|registry.digitalocean.com/scoutplan/app:'${TAG}'|' $GITHUB_WORKSPACE/config/kube/db-migrate.yml

      - name: Update deployment file
        run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|registry.digitalocean.com/scoutplan/app|registry.digitalocean.com/scoutplan/app:'${TAG}'|' $GITHUB_WORKSPACE/config/kube/deployment.yml

      - name: Update sidekiq file
        run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|registry.digitalocean.com/scoutplan/app|registry.digitalocean.com/scoutplan/app:'${TAG}'|' $GITHUB_WORKSPACE/config/kube/sidekiq.yml

      - name: Log into DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/scoutplan/app:$(echo $GITHUB_SHA | head -c7)

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 primary

      - name: Deploy app to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/config/kube/deployment.yml

      - name: Deploy Sidekiq to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/config/kube/sidekiq.yml

      - name: Verify deployment
        run: kubectl rollout status deployment/scoutplan-app

      - name: Report deployment to Honeybadger
        run: curl -g "https://api.honeybadger.io/v1/deploys?deploy[environment]=production&deploy[local_username]=system&deploy[revision]=$GITHUB_RUN_NUMBER&api_key=hbp_afiJuqUHfBDVMCvM3Kg3nO8T1vxvEV0KLTzi"
        
      - name: Prune the image repo
        uses: sergeysova/jq-action@v2
        with:
          run: |
            digests=$(doctl registry repository list-tags app --output json | jq ".[5:] | .[] | .tag " -r | tr '\n' ' ')
            if [ -n "$digests" ]; then doctl registry repository delete-tag app $digests --force; fi

      - name: Ping the home page
        run: curl -G https://go.scoutplan.org
